version: "3.8"

services:
  settee_django:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/settee_server
    depends_on:
      - settee_db
    command: ["./wait-for-it.sh", "settee_db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  settee_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword